Repository Nexters/phochak-server, pull requests merged in 2023-04, with the labels that each got.

#134 refactor: 게시글 신고시 신고 사유 제거
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/controller/PostController.java
  src/main/java/com/nexters/phochak/domain/ReportPost.java
  src/main/java/com/nexters/phochak/dto/request/ReportPostRequestDto.java
  src/main/java/com/nexters/phochak/service/NotifyService.java
  src/main/java/com/nexters/phochak/service/ReportPostService.java
  src/main/java/com/nexters/phochak/service/impl/PostBlockServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/ReportPostServiceImpl.java
  src/test/java/com/nexters/phochak/integration/PostNcpIntegrationTest.java
  src/test/java/com/nexters/phochak/integration/ReportPostServiceIntegrationTest.java
Labels: ♻️ 리팩토링

#141 feat: 게시글 조회 시 신고 누적된 게시글 노출 및 필드 추가
  src/main/java/com/nexters/phochak/domain/Post.java
  src/main/java/com/nexters/phochak/dto/PostFetchDto.java
  src/main/java/com/nexters/phochak/dto/response/PostPageResponseDto.java
  src/main/java/com/nexters/phochak/repository/impl/LikesCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/repository/impl/PostCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/service/impl/ReportPostServiceImpl.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
Labels: :sparkles: 기능 구현

#143 feat: AWS 서버에 배포되도록 파이프라인 구축
  .github/workflows/actions-merge.yml
Labels: 🧱 인프라

#149 chore: CD 파이프라인에서 NCP 서버 제거
  .github/workflows/actions-merge.yml
Labels: 🧱 인프라

#144 feat: 게시글 수정 구현
  README.md
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/controller/PostController.java
  src/main/java/com/nexters/phochak/domain/Hashtag.java
  src/main/java/com/nexters/phochak/domain/Post.java
  src/main/java/com/nexters/phochak/dto/request/PostUpdateRequestDto.java
  src/main/java/com/nexters/phochak/service/HashtagService.java
  src/main/java/com/nexters/phochak/service/PostService.java
  src/main/java/com/nexters/phochak/service/impl/HashtagServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/JwtTokenServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/PostServiceImpl.java
  src/main/resources/sql/V20220424_001_해시태그관련인덱스추가.sql
  src/test/java/com/nexters/phochak/integration/PostNcpIntegrationTest.java
Labels: :sparkles: 기능 구현

#152 feat: 탈퇴 유저에 탈퇴 일시 필드 추가하기
  src/main/java/com/nexters/phochak/domain/User.java
  src/main/resources/sql/V20230425_001_회원테이블_컬럼추가.sql
  src/test/java/com/nexters/phochak/integration/UserIntegrationTest.java
Labels: :sparkles: 기능 구현

#154 feat: AWS 서버 내에 로그 마운팅 설정
  .github/workflows/actions-merge.yml
Labels: 🧱 인프라

#156 fix: 좋아요한 게시글의 닉네임이 조회한 사람의 닉네임이 표시되는 버그 수정
  src/main/java/com/nexters/phochak/repository/impl/LikesCustomRepositoryImpl.java
Labels: 🐛 버그
