Repository Nexters/phochak-server, pull requests merged in 2023-02, with the labels that each got.

#35 feat: kakao OAuth flow 수정
  src/main/java/com/nexters/phochak/client/KakaoAccessTokenFeignClient.java
  src/main/java/com/nexters/phochak/controller/UserController.java
  src/main/java/com/nexters/phochak/dto/LoginRequestDto.java
  src/main/java/com/nexters/phochak/service/OAuthService.java
  src/main/java/com/nexters/phochak/service/UserService.java
  src/main/java/com/nexters/phochak/service/impl/AppleOAuthServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/KakaoOAuthServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/nexters/phochak/PhochakApplicationTests.java
  src/test/java/com/nexters/phochak/controller/UserControllerTest.java
Labels: 🚨 긴급

#40 [feat] RestDocs 에 누락된 항목 추가
  src/docs/asciidoc/likes.adoc
  src/docs/asciidoc/login.adoc
  src/docs/asciidoc/post.adoc
Labels: 🐛 버그, 🚨 긴급

#41 docs: Spring RestDocs host 정보 수정
  src/docs/asciidoc/likes.adoc
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/repository/impl/PostCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/specification/PostSortOption.java
  src/test/java/com/nexters/phochak/controller/LikesControllerTest.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
  src/test/java/com/nexters/phochak/controller/UserControllerTest.java
Labels: 📜 문서화, 🚨 긴급

#44 feat: Post 조회 시 hashtags 정보 추가
  src/main/java/com/nexters/phochak/domain/Hashtag.java
  src/main/java/com/nexters/phochak/domain/Post.java
  src/main/java/com/nexters/phochak/dto/response/PostPageResponseDto.java
  src/main/java/com/nexters/phochak/repository/impl/PostCustomRepositoryImpl.java
  src/main/resources/application.yml
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
Labels: :sparkles: 기능 구현

#37 feat: NCP를 활용한 streaming 구현
  build.gradle
  ncp/LambdaAutoEncodeActionFromS3.py
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/client/StorageBucketClient.java
  src/main/java/com/nexters/phochak/client/impl/NCPStorageClient.java
  src/main/java/com/nexters/phochak/config/ResourceDirectoryConfig.java
  src/main/java/com/nexters/phochak/controller/LikesController.java
  src/main/java/com/nexters/phochak/controller/PostController.java
  src/main/java/com/nexters/phochak/domain/Hashtag.java
  src/main/java/com/nexters/phochak/domain/Likes.java
  src/main/java/com/nexters/phochak/domain/Post.java
  src/main/java/com/nexters/phochak/domain/PostReport.java
  src/main/java/com/nexters/phochak/domain/Shorts.java
  src/main/java/com/nexters/phochak/dto/EncodingCallbackRequestDto.java
  src/main/java/com/nexters/phochak/dto/PostUploadKeyRequestDto.java
  src/main/java/com/nexters/phochak/dto/PostUploadKeyResponseDto.java
  src/main/java/com/nexters/phochak/dto/request/PostCreateRequestDto.java
  src/main/java/com/nexters/phochak/exception/CustomExceptionHandler.java
  src/main/java/com/nexters/phochak/repository/PostRepository.java
  src/main/java/com/nexters/phochak/repository/ShortsRepository.java
  src/main/java/com/nexters/phochak/service/HashtagService.java
  src/main/java/com/nexters/phochak/service/PostService.java
  src/main/java/com/nexters/phochak/service/ShortsService.java
  src/main/java/com/nexters/phochak/service/impl/HashtagServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/NCPShortsService.java
  src/main/java/com/nexters/phochak/service/impl/PostServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/ShortsService.java
  src/main/java/com/nexters/phochak/service/impl/ShortsServiceLocalStorage.java
  src/main/java/com/nexters/phochak/specification/ReportCategory.java
  src/main/java/com/nexters/phochak/specification/ReportCategoryEnum.java
  src/main/java/com/nexters/phochak/specification/ShortsStateEnum.java
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/nexters/phochak/controller/LikesControllerTest.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
  src/test/java/com/nexters/phochak/integration/LikesIntegrationTest.java
  src/test/java/com/nexters/phochak/integration/PostControllerIntegration.java
  src/test/java/com/nexters/phochak/integration/PostLocalStorageIntegrationTest.java
  src/test/java/com/nexters/phochak/integration/PostNcpIntegrationTest.java
  src/test/java/com/nexters/phochak/service/NCPShortsServiceTest.java
  src/test/java/com/nexters/phochak/service/PostServiceImplTest.java
  src/test/java/com/nexters/phochak/service/impl/HashtagServiceImplTest.java
Labels: :sparkles: 기능 구현

#55 docs: 서버 응답코드 문서화
  .gitignore
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/likes.adoc
  src/docs/asciidoc/login.adoc
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/exception/ResCode.java
  src/main/java/com/nexters/phochak/repository/impl/MediaFileLocalRepository.java
  src/main/java/com/nexters/phochak/service/impl/HashtagServiceImpl.java
  src/main/java/com/nexters/phochak/specification/OAuthProviderEnum.java
  src/test/java/com/nexters/phochak/docs/ResCodeDocs.java
  src/test/java/com/nexters/phochak/service/impl/HashtagServiceImplTest.java
Labels: 📜 문서화

#53 feat: 닉네임 중복 확인 기능 개발
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/com/nexters/phochak/controller/UserController.java
  src/main/java/com/nexters/phochak/dto/response/UserCheckResponseDto.java
  src/main/java/com/nexters/phochak/repository/UserRepository.java
  src/main/java/com/nexters/phochak/service/UserService.java
  src/main/java/com/nexters/phochak/service/impl/UserServiceImpl.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
  src/test/java/com/nexters/phochak/controller/UserControllerTest.java
  src/test/java/com/nexters/phochak/integration/UserIntegrationTest.java
Labels: :sparkles: 기능 구현

#64 fix: Latest로 2번째 요청 날릴 시 NPE 발생
  src/main/java/com/nexters/phochak/repository/impl/PostCustomRepositoryImpl.java
Labels: 🐛 버그

#69 refactor: 예외 응답시에도 data 필드 넣어주기
  src/main/java/com/nexters/phochak/dto/response/CommonResponse.java
  src/main/java/com/nexters/phochak/dto/response/ExceptionResponseDto.java
  src/main/java/com/nexters/phochak/exception/CustomExceptionHandler.java
  src/main/java/com/nexters/phochak/exception/PhochakException.java
Labels: ♻️ 리팩토링

#68 feat: 닉네임 변경 기능 개발
  src/docs/asciidoc/post.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/com/nexters/phochak/controller/UserController.java
  src/main/java/com/nexters/phochak/domain/User.java
  src/main/java/com/nexters/phochak/dto/request/NicknameModifyRequestDto.java
  src/main/java/com/nexters/phochak/exception/CustomExceptionHandler.java
  src/main/java/com/nexters/phochak/exception/PhochakException.java
  src/main/java/com/nexters/phochak/exception/ResCode.java
  src/main/java/com/nexters/phochak/repository/UserRepository.java
  src/main/java/com/nexters/phochak/service/UserService.java
  src/main/java/com/nexters/phochak/service/impl/HashtagServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/UserServiceImpl.java
  src/test/java/com/nexters/phochak/controller/UserControllerTest.java
  src/test/java/com/nexters/phochak/service/UserServiceTest.java
  src/test/java/com/nexters/phochak/service/impl/HashtagServiceImplTest.java
Labels: :sparkles: 기능 구현

#73 chore: Post 조회 응답 필드 정리
  src/main/java/com/nexters/phochak/domain/Shorts.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
Labels: ♻️ 리팩토링

#54 feat: error 발생 시 슬랙으로 로그 전송
  build.gradle
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: :sparkles: 기능 구현

#71 feat: 새로운 해시태그 정책 반영
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/domain/Hashtag.java
  src/main/java/com/nexters/phochak/service/impl/HashtagServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/UserServiceImpl.java
  src/test/java/com/nexters/phochak/service/impl/HashtagServiceImplTest.java
Labels: :sparkles: 기능 구현

#74 feat: 유저 정보 조회용 API 구현
  src/docs/asciidoc/user.adoc
  src/main/java/com/nexters/phochak/controller/UserController.java
  src/main/java/com/nexters/phochak/dto/response/UserInfoResponseDto.java
  src/main/java/com/nexters/phochak/service/UserService.java
  src/main/java/com/nexters/phochak/service/impl/UserServiceImpl.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
  src/test/java/com/nexters/phochak/controller/UserControllerTest.java
Labels: :sparkles: 기능 구현

#79 feat: 내가 업로드한 게시글 보기
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/controller/PostController.java
  src/main/java/com/nexters/phochak/dto/PostFetchCommand.java
  src/main/java/com/nexters/phochak/dto/request/CustomCursor.java
  src/main/java/com/nexters/phochak/dto/request/PostFilter.java
  src/main/java/com/nexters/phochak/repository/LikesRepository.java
  src/main/java/com/nexters/phochak/repository/PostCustomRepository.java
  src/main/java/com/nexters/phochak/repository/impl/PostCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/service/PostService.java
  src/main/java/com/nexters/phochak/service/impl/PhochakServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/PostServiceImpl.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
  src/test/java/com/nexters/phochak/integration/LikesIntegrationTest.java
  src/test/java/com/nexters/phochak/service/LikesServiceImplTest.java
Labels: :sparkles: 기능 구현

#83 feat: 유저페이지 정보 조회 API 구현
  src/docs/asciidoc/user.adoc
  src/main/java/com/nexters/phochak/controller/UserController.java
  src/main/java/com/nexters/phochak/dto/response/UserInfoResponseDto.java
  src/main/java/com/nexters/phochak/service/UserService.java
  src/main/java/com/nexters/phochak/service/impl/UserServiceImpl.java
  src/test/java/com/nexters/phochak/controller/UserControllerTest.java
Labels: :sparkles: 기능 구현

#85 feat: 게시글 신고 기능 구현
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/client/SlackPostReportFeignClient.java
  src/main/java/com/nexters/phochak/controller/PostController.java
  src/main/java/com/nexters/phochak/domain/PostReport.java
  src/main/java/com/nexters/phochak/domain/ReportPost.java
  src/main/java/com/nexters/phochak/dto/SlackMessageFormDto.java
  src/main/java/com/nexters/phochak/dto/request/ReportPostRequestDto.java
  src/main/java/com/nexters/phochak/repository/ReportPostRepository.java
  src/main/java/com/nexters/phochak/service/ReportPostService.java
  src/main/java/com/nexters/phochak/service/impl/ReportPostServiceImpl.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/nexters/phochak/integration/PostNcpIntegrationTest.java
Labels: :sparkles: 기능 구현

#81 feat: Access, Refresh token 재발급 구현
  build.gradle
  src/docs/asciidoc/login.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/com/nexters/phochak/auth/aspect/AuthAspect.java
  src/main/java/com/nexters/phochak/config/EmbeddedRedisConfig.java
  src/main/java/com/nexters/phochak/config/RedisConfig.java
  src/main/java/com/nexters/phochak/controller/UserController.java
  src/main/java/com/nexters/phochak/dto/request/ReissueTokenRequestDto.java
  src/main/java/com/nexters/phochak/dto/response/JwtResponseDto.java
  src/main/java/com/nexters/phochak/repository/RefreshTokenRepository.java
  src/main/java/com/nexters/phochak/repository/impl/RedisRefreshTokenRepository.java
  src/main/java/com/nexters/phochak/service/JwtTokenService.java
  src/main/java/com/nexters/phochak/service/impl/JwtTokenServiceImpl.java
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/nexters/phochak/auth/aspect/AuthAspectTest.java
  src/test/java/com/nexters/phochak/controller/UserControllerTest.java
  src/test/java/com/nexters/phochak/docs/ResCodeDocs.java
  src/test/java/com/nexters/phochak/integration/AuthIntegrationTest.java
  src/test/java/com/nexters/phochak/integration/LikesIntegrationTest.java
  src/test/java/com/nexters/phochak/integration/PostLocalStorageIntegrationTest.java
  src/test/java/com/nexters/phochak/integration/PostNcpIntegrationTest.java
  src/test/java/com/nexters/phochak/repository/RedisRefreshTokenRepositoryTest.java
Labels: :sparkles: 기능 구현

#87 feat: 로그아웃 구현
  src/docs/asciidoc/user.adoc
  src/main/java/com/nexters/phochak/controller/UserController.java
  src/main/java/com/nexters/phochak/dto/request/LogoutRequestDto.java
  src/main/java/com/nexters/phochak/service/JwtTokenService.java
  src/main/java/com/nexters/phochak/service/impl/JwtTokenServiceImpl.java
  src/test/java/com/nexters/phochak/integration/AuthIntegrationTest.java
Labels: :sparkles: 기능 구현

#89 fix: Redis 운영환경 및 테스트 설정 정보 수정
  src/main/java/com/nexters/phochak/config/EmbeddedRedisConfig.java
  src/main/java/com/nexters/phochak/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🐛 버그, 🚨 긴급

#93 feat: 게시글 조회수 반영 API 작성
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/controller/PostController.java
  src/main/java/com/nexters/phochak/exception/CustomExceptionHandler.java
  src/main/java/com/nexters/phochak/repository/PostRepository.java
  src/main/java/com/nexters/phochak/service/PostService.java
  src/main/java/com/nexters/phochak/service/impl/PostServiceImpl.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
  src/test/java/com/nexters/phochak/integration/PostIntegrationTest.java
  src/test/java/com/nexters/phochak/service/PostServiceImplTest.java
Labels: :sparkles: 기능 구현

#91 feat: 내가 포착(좋아요)한 게시글 보기
  build.gradle
  src/docs/asciidoc/post.adoc
  src/main/java/com/nexters/phochak/domain/Shorts.java
  src/main/java/com/nexters/phochak/domain/User.java
  src/main/java/com/nexters/phochak/dto/HashtagFetchDto.java
  src/main/java/com/nexters/phochak/dto/LikesFetchDto.java
  src/main/java/com/nexters/phochak/dto/PostFetchCommand.java
  src/main/java/com/nexters/phochak/dto/PostFetchDto.java
  src/main/java/com/nexters/phochak/dto/request/PostFilter.java
  src/main/java/com/nexters/phochak/dto/response/PostPageResponseDto.java
  src/main/java/com/nexters/phochak/repository/HashtagCustomRepository.java
  src/main/java/com/nexters/phochak/repository/HashtagRepository.java
  src/main/java/com/nexters/phochak/repository/LikesCustomRepository.java
  src/main/java/com/nexters/phochak/repository/LikesRepository.java
  src/main/java/com/nexters/phochak/repository/PostCustomRepository.java
  src/main/java/com/nexters/phochak/repository/impl/HashtagCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/repository/impl/LikesCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/repository/impl/PostCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/service/HashtagService.java
  src/main/java/com/nexters/phochak/service/LikesService.java
  src/main/java/com/nexters/phochak/service/impl/HashtagServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/LikeServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/PostServiceImpl.java
  src/test/java/com/nexters/phochak/controller/PostControllerTest.java
Labels: :sparkles: 기능 구현

#94 docs: 닉네임 변경 api 문서 수정
  src/test/java/com/nexters/phochak/controller/UserControllerTest.java
Labels: 📜 문서화

#99 fix: asciidocter 관련 build.gradle 수정
  build.gradle
  src/docs/asciidoc/index.adoc
Labels: 🐛 버그, 📜 문서화

#101 docs: 토큰 재발급 문서 수정
  src/docs/asciidoc/login.adoc
  src/docs/asciidoc/user.adoc
Labels: 📜 문서화

#104 feat: actions를 활용한 CI 구축
  .github/workflows/actions.yml
Labels: :sparkles: 기능 구현

#102 feat: 운영 데이터베이스 DDL 작성 및 필요한 인덱스 정의
  src/main/java/com/nexters/phochak/dto/LikesFetchDto.java
  src/main/java/com/nexters/phochak/dto/PostFetchCommand.java
  src/main/java/com/nexters/phochak/dto/PostFetchDto.java
  src/main/java/com/nexters/phochak/dto/QuerydslFetchDto.java
  src/main/java/com/nexters/phochak/dto/response/PostPageResponseDto.java
  src/main/java/com/nexters/phochak/repository/PostCustomRepository.java
  src/main/java/com/nexters/phochak/repository/impl/LikesCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/repository/impl/PostCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/service/LikesService.java
  src/main/java/com/nexters/phochak/service/impl/LikeServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/PostServiceImpl.java
  src/main/resources/sql/V20220225_001_초기테이블_schema.sql
  src/main/resources/sql/V20220225_002_인덱스추가.sql
Labels: :sparkles: 기능 구현

#107 feat: 회원 탈퇴 구현
  src/docs/asciidoc/user.adoc
  src/main/java/com/nexters/phochak/client/StorageBucketClient.java
  src/main/java/com/nexters/phochak/client/impl/NCPStorageClient.java
  src/main/java/com/nexters/phochak/controller/UserController.java
  src/main/java/com/nexters/phochak/domain/Shorts.java
  src/main/java/com/nexters/phochak/domain/User.java
  src/main/java/com/nexters/phochak/dto/request/NicknameModifyRequestDto.java
  src/main/java/com/nexters/phochak/dto/request/WithdrawRequestDto.java
  src/main/java/com/nexters/phochak/repository/HashtagRepository.java
  src/main/java/com/nexters/phochak/repository/PostRepository.java
  src/main/java/com/nexters/phochak/repository/ShortsRepository.java
  src/main/java/com/nexters/phochak/service/PostService.java
  src/main/java/com/nexters/phochak/service/UserService.java
  src/main/java/com/nexters/phochak/service/impl/NCPShortsService.java
  src/main/java/com/nexters/phochak/service/impl/PostServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/UserServiceImpl.java
  src/test/java/com/nexters/phochak/integration/AuthIntegrationTest.java
Labels: :sparkles: 기능 구현

#106 feat: logback을 통한 운영 로그 수집
  src/main/java/com/nexters/phochak/service/impl/JwtTokenServiceImpl.java
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring.xml
Labels: :sparkles: 기능 구현
