Repository Nexters/phochak-server, pull requests merged in 2023-03, with the labels that each got.

#109 fix: 좋아요 동시성 문제 해결을 위한 unique index 추가
  src/main/java/com/nexters/phochak/controller/LikesController.java
  src/main/java/com/nexters/phochak/domain/Likes.java
  src/main/resources/sql/V20220225_002_인덱스추가.sql
Labels: 🐛 버그

#114 fix: JWT body 요청시 Bearer prefix 미포함 이슈 해결
  src/main/java/com/nexters/phochak/service/impl/JwtTokenServiceImpl.java
  src/test/java/com/nexters/phochak/integration/AuthIntegrationTest.java
Labels: 🐛 버그, 🚨 긴급

#111 chore: CI/CD 파이프라인 구축
  .github/workflows/actions-merge.yml
  .github/workflows/actions-pr.yml
  build.gradle
Labels: 🧱 인프라

#116 refactor: Entity에 사용되는 인덱스 정의 및 클래스명 수정
  src/main/java/com/nexters/phochak/controller/LikesController.java
  src/main/java/com/nexters/phochak/domain/Likes.java
  src/main/java/com/nexters/phochak/domain/Post.java
  src/main/java/com/nexters/phochak/domain/Shorts.java
  src/main/java/com/nexters/phochak/repository/impl/LikesCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/service/LikesService.java
  src/main/java/com/nexters/phochak/service/PhochakService.java
  src/main/java/com/nexters/phochak/service/impl/LikeServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/PhochakServiceImpl.java
  src/main/resources/sql/V20220225_001_초기테이블_schema.sql
  src/main/resources/sql/V20220225_002_인덱스추가.sql
  src/main/resources/sql/data.sql
  src/test/java/com/nexters/phochak/service/HashtagServiceTest.java
  src/test/java/com/nexters/phochak/service/LikesServiceTest.java
  src/test/java/com/nexters/phochak/service/PostServiceTest.java
Labels: ♻️ 리팩토링

#117 feat: CD job 실행 시 기존 이미지 삭제 처리하기
  .github/workflows/actions-merge.yml
Labels: :sparkles: 기능 구현

#119 feat: jib으로 이미지 생성 시 생성시간 표시하도록 수정
  build.gradle
Labels: :sparkles: 기능 구현

#121 refactor: 포착 취소시 불필요한 query 제거
  src/main/java/com/nexters/phochak/service/impl/LikeServiceImpl.java
  src/test/java/com/nexters/phochak/service/LikesServiceTest.java
Labels: ♻️ 리팩토링

#124 feat: 컨테이너 환경의 로그 수집
  .github/workflows/actions-merge.yml
Labels: :sparkles: 기능 구현

#129 feat: 신고 시 게시글 노출하지 않기
  src/main/java/com/nexters/phochak/config/AsyncConfig.java
  src/main/java/com/nexters/phochak/controller/LikesController.java
  src/main/java/com/nexters/phochak/controller/PostController.java
  src/main/java/com/nexters/phochak/domain/Post.java
  src/main/java/com/nexters/phochak/domain/ReportPost.java
  src/main/java/com/nexters/phochak/dto/SlackMessageFormDto.java
  src/main/java/com/nexters/phochak/exception/ResCode.java
  src/main/java/com/nexters/phochak/repository/ReportPostRepository.java
  src/main/java/com/nexters/phochak/repository/impl/LikesCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/repository/impl/PostCustomRepositoryImpl.java
  src/main/java/com/nexters/phochak/service/NotifyService.java
  src/main/java/com/nexters/phochak/service/ReportPostService.java
  src/main/java/com/nexters/phochak/service/impl/LikeServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/PostBlockServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/PostServiceImpl.java
  src/main/java/com/nexters/phochak/service/impl/ReportPostServiceImpl.java
  src/main/resources/sql/V20220305_001_신고관련속성추가.sql
  src/test/java/com/nexters/phochak/integration/PostNcpIntegrationTest.java
  src/test/java/com/nexters/phochak/integration/ReportPostServiceIntegrationTest.java
  src/test/java/com/nexters/phochak/service/LikesServiceTest.java
Labels: :sparkles: 기능 구현
